import { SessionProvider } from "next-auth/react";
import { Inter } from "next/font/google";
import { CartProvider } from "../components/(provider)/cartProvider";
import Footer from "../components/(structure)/Footer";
import Header from "../components/(structure)/Header";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Arneis - Vente de mobilier artisanal",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="lightMode">
      <SessionProvider>
        <CartProvider>
          <body className={inter.className}>
            <Header />
            {children}
            <Footer />
          </body>
        </CartProvider>
      </SessionProvider>
    </html>
  );
}
